[build]
    command = "npm run build"
    publish = "dist"
    functions = "src/functions"

[context.production.environment]
    ELEVENTY_ENV = "production"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "no-referrer-when-downgrade"
        Permissions-Policy = "interest-cohort=()"

[[redirects]]
    from = "https://afnizarnur.netlify.com/*"
    to = "https://afnizarnur.com/:splat"
    status = 301
    force = true

[[redirects]]
    from = "*"
    to = "/404"
    status = 404
