[[redirects]]
  from = "/dribbble"
  to = "https://dribbble.com/afnizarnur"
  status = 200
  force = true

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/afnizarnur"
  status = 200
  force = true
